/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "tutorials/intro",
    {
      type: "category",
      label: "1. Environment Setup",
      link: {
        type: "doc",
        id: "tutorials/environment-setup/intro",
      },
      items: [
        {
          type: "doc",
          label: "1.1 Initialize Hardhat",
          id: "tutorials/environment-setup/initialize-hardhat",
        },
        {
          type: "doc",
          label: "1.2 Gearbox SDK And Mainnet Forking",
          id: "tutorials/environment-setup/gearbox-sdk",
        },
        {
          type: "doc",
          label: "1.3 A Simple Example",
          id: "tutorials/environment-setup/a-simple-example",
        },
      ],
    },
    {
      type: "category",
      label: "2. Gearbox Discovery",
      link: {
        type: "doc",
        id: "tutorials/gearbox-discovery/gearbox-discovery",
      },
      items: [
        {
          type: "doc",
          label: "2.1 Architecture",
          id: "tutorials/gearbox-discovery/architecture",
        },
        {
          type: "doc",
          label: "2.2 Gearbox Core",
          id: "tutorials/gearbox-discovery/gearbox-core",
        },
        {
          type: "doc",
          label: "2.3 Gearbox Pool",
          id: "tutorials/gearbox-discovery/gearbox-pools",
        },
        {
          type: "category",
          label: "2.4 Extracting Data",
          link: {
            type: "doc",
            id: "tutorials/gearbox-discovery/extracting-data/extracting-data",
          },
          items: [
            {
              type: "doc",
              label: "2.4.1 Get Opened Accounts",
              id: "tutorials/gearbox-discovery/extracting-data/get-opened-accounts"
            }
          ]
        }
      ],
    },
  ],
};

module.exports = sidebars;
