/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '1. Setting Up Environment',
      link: {
        type: 'doc',
        id: 'setting-up-environment/setting-up-environment'
      },
      items: [
        {
          type: 'doc',
          label: '1.1 Initialize Hardhat',
          id: 'setting-up-environment/initialize-hardhat'
        },
        {
          type: 'doc',
          label: '1.2 Gearbox SDK And Mainnet Forking',
          id: 'setting-up-environment/gearbox-sdk'
        },
        {
          type: 'doc',
          label: '1.3 A Simple Example',
          id: 'setting-up-environment/a-simple-example'
        }
      ],
    },
    {
      type: 'category',
      label: '2. Gearbox Discovery',
      link: {
        type: 'doc',
        id: 'gearbox-discovery/gearbox-discovery'
      },
      items: [
        {
          type: 'doc',
          label: '2.1 Architecture',
          id: 'gearbox-discovery/architecture'
        },
        {
          type: 'doc',
          label: '2.2 Core',
          id: 'gearbox-discovery/gearbox-core'
        }
      ],
    },
  ],
};

module.exports = sidebars;
